python_web/basics/carcollection/carcollection/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('carcollection.car_app.urls'))
]

python_web/basics/carcollection/carcollection/car_app/models/car_model.py
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator
from django.db import models


class Car(models.Model):
    CAR_TYPE_MAX_LEN = 10

    MODEL_MAX_LEN = 20
    MODEL_MIN_LEN = 2

    YEAR_MANUFACTURED_MIN_VAL = 1980
    YEAR_MANUFACTURED_MAX_VAL = 2049
    YEAR_MANUFACTURED_ERR_MSG = f"Year must be between {YEAR_MANUFACTURED_MIN_VAL} and {YEAR_MANUFACTURED_MAX_VAL}"

    SPORTS_CAR = 'Sports Car'
    PICKUP_TRUCK = 'Pickup'
    CROSSOVER_SUV = 'Crossover'
    MINIBUS = 'Minibus'
    OTHER = 'Other'
    DEFAULT = '----------'

    CAR_TYPES = [
        (SPORTS_CAR, 'Sports Car'),
        (PICKUP_TRUCK, 'Pickup'),
        (CROSSOVER_SUV, 'Crossover'),
        (MINIBUS, 'Minibus'),
        (OTHER, 'Other'),
        (DEFAULT, '---------')

    ]

    type = models.CharField(
        blank=False,
        null=False,
        max_length=CAR_TYPE_MAX_LEN,
        choices=CAR_TYPES,
        default=DEFAULT,
        verbose_name='Type'
    )

    model = models.CharField(
        blank=False,
        null=False,
        max_length=MODEL_MAX_LEN,
        validators=[MinLengthValidator(
            MODEL_MIN_LEN,
            f'Model name should be at least {MODEL_MIN_LEN} long.')
        ],
        verbose_name='Model'
    )

    year = models.IntegerField(
        blank=False,
        null=False,
        validators=[
            MinValueValidator(YEAR_MANUFACTURED_MIN_VAL,
                              YEAR_MANUFACTURED_ERR_MSG),
            MaxValueValidator(YEAR_MANUFACTURED_MAX_VAL,
                              YEAR_MANUFACTURED_ERR_MSG),
        ],
        verbose_name='Year'
    )

    image_url = models.URLField(
        blank=False,
        null=False,
        verbose_name='Image URL'
    )

    price = models.DecimalField(
        blank=False,
        null=False,
        max_digits=200,
        decimal_places=3,
        validators=[MinValueValidator(1), ],
        verbose_name='Price'
    )

python_web/basics/carcollection/carcollection/car_app/models/user_model.py
from django.core.validators import MinLengthValidator, MaxValueValidator, MinValueValidator
from django.db import models


class Profile(models.Model):
    MIN_LEN_UN = 2
    MIN_AGE = 18
    MAX_AGE = 150
    MAX_LEN_FN = 30
    MAX_LEN_LN = 30
    MAX_LEN_PW = 128

    username = models.CharField(
        blank=False,
        null=False,
        max_length=10,
        validators=[
            MinLengthValidator(MIN_LEN_UN, f"The username must be a minimum of {MIN_LEN_UN} chars")
        ],
    )
    email = models.EmailField(
        blank=False,
        null=False,
    )

    age = models.IntegerField(
        blank=False,
        null=False,
        validators=[
            MaxValueValidator(MAX_AGE, "It is not safe to drive"),
            MinValueValidator(MIN_AGE, f"You must be of age to register")
        ]
    )

    password = models.CharField(
        blank=False,
        null=False,
        max_length=MAX_LEN_PW
    )

    first_name = models.CharField(
        blank=True,
        null=True,
        max_length=MAX_LEN_FN,
        verbose_name="First Name"

    )

    last_name = models.CharField(
        blank=True,
        null=True,
        max_length=MAX_LEN_LN,
        verbose_name="Last Name"

    )

    image_url = models.URLField(
        blank=True,
        null=False,
        verbose_name="Profile Picture"
    )

python_web/basics/carcollection/templates/car-create.html
{% extends 'shared/nav.html' %}
{% block site_content %}
    <section id="create-page" class="auth">
        <!-- create car form -->
        <form id="create" method="post" action="{% url 'add-car' %}">
            <div class="container">
                <h1 class="form-create-headline">Create Car</h1>
                {{ form }}
                {% csrf_token %}
                <input class="btn" type="submit" value="Create Car">
            </div>
        </form>
    </section>
{% endblock %}

python_web/basics/carcollection/templates/car-delete.html
{% extends 'shared/nav.html' %}
{% block site_content %}

    <!-- edit game form -->
    <section id="delete-page" class="auth">
        <form id="delete" method="post" action="{% url 'delete-car' car.id %}">
            <div class="container">
                <h1>Delete Car</h1>
                 {{ form }}
                {% csrf_token %}
                <input class="btn submit" type="submit" value="Delete Car">
            </div>
        </form>
    </section>
{% endblock %}

python_web/basics/carcollection/templates/car-details.html
{% extends 'shared/nav.html' %}
{% block site_content %}
    <!-- details section -->
    <section id="car-details">
        <h1>Car Details</h1>
        <div class="info-section">
            <div class="car-header">
                <!-- car image -->
                <img class="car-img"
                     src="{{ car.image_url }}"
                     alt='car image'/>
                <!-- type and model -->
                <h1>{{ car.type }}</h1>
                <!-- car model -->
                <p><span class="description">Model: {{ car.model }}</span></p>
                <!-- car year -->
                <p><span class="description">Year: {{ car.year }}</span></p>
                <!-- car price -->
                <p><span class="description">Price: {{ car.price }}</span></p>
            </div>
            <!-- Edit/Delete buttons -->
            <div class="buttons">
                <a href="{% url 'edit-car' car.id %}" class="edit-button">Edit</a>
                <a href="{% url 'delete-car' car.id %}" class="delete-button">Delete</a>
            </div>
        </div>
    </section>
{% endblock %}

python_web/basics/carcollection/templates/car-edit.html
{% extends 'shared/nav.html' %}
{% block site_content %}
    <!-- edit car form -->
    <section id="create-page" class="auth">
        <form id="create" method="post" action="{% url 'edit-car' car.id %}">
            <div class="container">
                <h1>Edit Car</h1>
                {{ form }}
                {% csrf_token %}
                <input class="btn submit" type="submit" value="Edit Car">
            </div>
        </form>
    </section>
{% endblock %}

python_web/basics/carcollection/templates/catalogue.html
{% extends 'shared/nav.html' %}
{% block site_content %}
    <!-- Display paragraph: If there are no cars yet-->
        {% if not cars %}
        <p class="no-articles">No cars yet</p>
        <!-- Display div "car" with information about every car (if any)-->
        {% else %}
            <section id="catalogue">
                <h1>Total cars: {{ cars_cnt }}</h1>
                {% for car in cars %}
                    <div class="car-card">
                        <div class="image-wrap">
                            <img src="{{ car.image_url }}"
                                alt="{{ car.type }}">
                        </div>
                        <!-- car type -->
                        <h3>{{ car.type }}</h3>
                        <!-- car model -->
                        <h1>{{ car.model }}</h1>
                        <div class="details-buttons">
                            <!-- car details button -->
                            <a href="{% url 'details-car' car.id %}" class="details-btn">Details</a>
                        </div>
                    </div>
                    {% endfor %}
        {% endif %}
        </section>
{% endblock %}

python_web/basics/carcollection/templates/index.html
{% extends 'shared/nav.html' %}
{% block site_content %}
    <section id="index-headline">
        <div class="index-message">
            <h2>Our <span>cars</span> collection is expecting you!</h2>
        </div>
        <img src="/static/images/car-index.png" alt="car">
    </section>
{% endblock %}

python_web/basics/carcollection/templates/profile-create.html
{% extends 'shared/nav.html' %}
{% block site_content %}
    <!-- create profile form -->
    <section id="register-page" class="content auth">
        <form id="register" method="post" action="{% url 'create-profile' %}">
            <div class="container">
                <div class="brand-logo"></div>
                <h1>Create Profile</h1>
                {{ form }}
                {% csrf_token %}
                <input class="btn submit" type="submit" value="Create Profile">
            </div>
        </form>
    </section>
{% endblock %}

python_web/basics/carcollection/templates/profile-delete.html
{% extends 'shared/nav.html' %}
{% block site_content %}
  <section id="create-page" class="auth">

      <div class="container">
        <h1>Are you sure you want to delete your profile?</h1>
          <!-- Delete Profile Form -->
        <form id='delete' method="post" action="{% url 'delete-profile' %}">
        <!-- Confirm Button -->
        <input class="btn submit" type="submit" value="Yes">
        {% csrf_token %}

        </form>
      </div>
    <!-- End Delete Profile Form -->
  </section>
{% endblock %}

python_web/basics/carcollection/templates/profile-details.html
{% extends 'shared/nav.html' %}
{% block site_content %}

    <!-- profile details section -->
    <section id="car-details">
        <h1>Profile Details</h1>
        <div class="info-section">
            <div class="car-header">
                <!-- default profile image (if the user does NOT have any)-->
                {% if not profile.image_url %}
                    <img class="car-img" src="/static/images/default-profile.png" alt='profile-image'/>
                <!-- if the user has a profile image -->
                {% else %}
                    <img class="car-img" src="{{ profile.image_url }}" alt='profile-image'/>
                {% endif %}


                <!-- user full name (if any) -->
                {% if profile.first_name and profile.last_name %}
                <h1>  {{ profile.first_name }} {{ profile.last_name }}</h1>
                {% elif profile.first_name %}
                <h1>{{ profile.first_name }}</h1> 
                {% elif profile.last_name %}
                <h1>{{ profile.last_name }}</h1>
                {% else %}
                <h1></h1>
                {% endif %}                 
                <!-- user username -->
                <p class="description">Username: {{ profile.username }}</p>
                <!-- user email -->
                <p class="description">Email: {{ profile.email }}</p>
                <!-- user age -->
                <p class="description">Age: {{ profile.age }}</p>
                <!-- total price of all cars -->
                <p class="description">Total price: {{ cars_value }}</p>
                <!-- Edit/Delete buttons -->
                <div class="buttons">
                    <a href="{% url 'edit-profile' %}" class="edit-button">Edit</a>
                    <a href="{% url 'delete-profile' %}" class="delete-button">Delete</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

python_web/basics/carcollection/templates/profile-edit.html
{% extends 'shared/nav.html' %}
{% block site_content %}
    <!-- edit profile form -->
    <section id="register-page" class="content auth">
        <form id="register" method="post" action="{% url 'edit-profile' %}">
            <div class="container">
                <h1>Edit Profile</h1>
                <label for="id_username">Username:</label>
                {{ form.username }}
                <label for="id_email">Email:</label>
                {{ form.email }}
                <label for="id_age">Age:</label>
                {{ form.age }}
                <label for="id_password">Password:</label>
                <input type="password" name="password" value="{{ form.password.value|slice:'20' }}" required="" id="id_password">
                <label for="id_first_name">First Name:</label>
                {{ form.first_name}}
                <label for="id_last_name">Last Name:</label>
                {{ form.last_name}}
                <label for="id_image_url">Profile Picture:</label>
                {{ form.image_url}}
                <!-- {{ form }} -->
                {% csrf_token %}
                <input class="btn" type="submit" value="Edit Profile">
            </div>
        </form>
    </section>
{% endblock %}