python_web/basics/music_app/music_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('music_app.authentication.urls')),
    path('user/', include('music_app.user.urls')),
    path('album/', include('music_app.albums.urls')),

]

python_web/basics/music_app/music_app/albums/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth.models import User
# Create your models here.
from django.db.models import constraints
POP = "Pop Music"
JAZZ = "Jazz Music"
RNB = "R&B Music"
ROCK = "Rock Music"
COUNTRY = "Country Music"
DANCE = "Dance Music"
HIPHOP = "Hip Hop Music"
OTHER = "Other"
DEFAULT = "---------"

CHOICES_MUSIC = (
    (POP, "Pop Music"),
    (JAZZ, "Jazz Music"),
    (RNB, "R&B Music"),
    (ROCK, "Rock Music"),
    (COUNTRY, "Country Music"),
    (DANCE, "Dance Music"),
    (HIPHOP, "Hip Hop Music"),
    (OTHER, "Other"),
    (DEFAULT, "---------")
)


class Album(models.Model):
    album_name = models.CharField(
        blank=False,
        max_length=30,
    )

    artist = models.CharField(
        blank=False,
        max_length=30,
    )

    genre = models.CharField(
        blank=False,
        choices=CHOICES_MUSIC,
        default=DEFAULT,
        max_length=30
    )

    description = models.TextField(
        blank=True
    )

    image_url = models.URLField(
        blank=False
    )

    price = models.DecimalField(
        max_digits=20,
        decimal_places=2,
        validators=[
            MinValueValidator(0)],
    )

    users  = models.ManyToManyField(User)
    

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['album_name', 'artist'], name='unique_album'),
        ]

python_web/basics/music_app/templates/add-album.html
{% extends 'base.html' %}
{% block site_content %}
<!--Create Page-->
<section class="createPage">
    <form method="post" action="{% url 'add album' %}">
        <fieldset>
            <legend>Add Album</legend>
            <div class="container">
                {{ form }}
                {% csrf_token %}
                <!-- Button for Adding Album -->
                <button class="add-album" type="submit">Add New Album</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

python_web/basics/music_app/templates/album-details.html
{% extends 'base.html' %}
{% block site_content %}
<!--Details Page-->
<section id="detailsPage">
    <div class="wrapper">

        <div class="albumCover">
            <!-- Album Image -->
            <img src='{{ album.image_url }}' alt="Cover Image">
        </div>

        <div class="albumInfo">

            <div class="albumText">
                <!-- Album Info -->
                <h1>Name: {{ album.album_name }}</h1>
                <h3>Artist: {{ album.artist }}</h3>
                <h4>Genre: {{ album.genre }}</h4>
                <h4>Price: ${{ album.price }}</h4>
                <p>{{ album.description }}</p>
            </div>
            {% if user.is_authenticated and has_permission %}
            <div class="actionBtn">
                <!-- Album Buttons -->
                <a href="{% url 'edit album' album.id %}" class="edit">Edit</a>
                <a href="{% url 'delete album' album.id %}" class="remove">Delete</a>
            </div>
            {% endif %}

        </div>
    </div>
</section>
{% endblock %}

python_web/basics/music_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <title>{% block title %}My Music App{% endblock %}</title>
    <!-- Static Load -->
    <link rel="stylesheet" href="/static/css/style.css" />
</head>
{% load lookup %}

<body>
    <div id="box">
        <!-- Navigation Bar -->
        <header>
            <nav>
                <img src="/static/images/headphones.png" alt="headphones">
                <a href="{% url 'home' %}">Home</a>
                <div class="dropdown">
                    <a href="{% url 'show albums' %}">Browse</a>
                    <div class="dropdown-content" id="genreDropdown">
                        {% for genre in genres %}
                        {% with genre|lookup:'genre' as target_genre %}
                        <a href=" {% url 'filter genres' target_genre %}">{{ target_genre }}</a>
                        {% endwith %}
                        {% endfor %}
                    </div>
                </div>
                <ul>
                    <!--Only for user with created profile-->
                    <li>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a href="{% url 'add album' %}">Create Album</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}?next=/">Logout</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'show profile' %}">Profile</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Profile</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <!-- End Navigation Bar -->

        {% block site_content %}
        {% endblock %}
        {% block pagination %}
        {% endblock %}
        <!-- Footer -->
        <footer>
            <div>
                &copy;SoftUni Team 2022. All rights reserved.
            </div>
        </footer>
        <!-- End Footer -->

    </div>

</body>

</html>

python_web/basics/music_app/templates/browse-albums.html
{% extends 'base.html' %}
{% block title %} Browse Albums {% endblock %}
{% block site_content %}
<div class="album-container">
    {% for album in page_obj %}
    <div class="card-box">
        <img src="{{ album.image_url }}" alt="Cover Image">
        <div>
            <div class="text-center">
                <p class="name">Name: {{ album.album_name }}</p>
                <p class="artist">Artist: {{ album.artist }}</p>
                <p class="genre">{{ album.genre }}</p>
                <p class="price">Price: ${{ album.price }}</p>
            </div>
            <div class="btn-group">
                <a href="{% url 'details album' album.id %}">Details</a>
            </div>
        </div>
    </div>
    {% endfor %}


</div>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</section>

{% endblock %}

python_web/basics/music_app/templates/delete-album.html
{% extends 'base.html' %}
{% block site_content %}
<!--Edit Page-->
<section class="editPage">
    <form method="post" action="{% url 'delete album' album.id %}">
        <fieldset>
            <legend>Delete Album</legend>
            <div class="container">

                {{ form }}
                {% csrf_token %}

                <!-- Button for Deleting an Album -->
                <button class="delete-album" type="submit">Delete Album</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

python_web/basics/music_app/templates/edit-album.html
{% extends 'base.html' %}
{% block site_content %}
<!--Edit Page-->
<section class="editPage">
    <form method="post" action="{% url 'edit album' album.id %}">
        <fieldset>
            <legend>Edit Album</legend>
            <div class="container">
                {{ form }}
                {% csrf_token %}
                <!-- Button for Editing Album -->
                <button class="edit-album" type="submit">Edit Album</button>
            </div>
        </fieldset>
    </form>
</section>
{% endblock %}

python_web/basics/music_app/templates/home-no-profile.html
{% extends 'base.html' %}
{% block title %} Homepage {% endblock %}
{% block site_content %}
<!--Home Page-->
<div class="container-inline">
    <section id="welcomePage">
        <div id="welcome-message">
            <h1>Welcome to</h1>
            <h1>My Music App!</h1>
        </div>
        <div class="music-img">
            <img src="/static/images/musicIcons.webp" alt="music-icon">
        </div>
    </section>
    <!-- Registration -->
    <section id="registerPage">
        {% include template_name %}
    </section>
</div>
{% endblock %}

python_web/basics/music_app/templates/home-with-profile.html
{% extends 'base.html' %}
{% block site_content %}
<!-- Catalog with Albums-->
<section id="catalogPage">
    {% if not albums %}
    <!--  If No albums in catalog -->
    <p>No Albums in Catalog!</p>
    {% else %}
    <!-- If albums in catalog -->
    <h1>All Albums</h1>
    {% for album in albums %}
    <!-- First Card-Box in catalog -->
    <div class="card-box">
        <img src="{{ album.image_url }}" alt="Cover Image">
        <div>
            <div class="text-center">
                <p class="name">Name: {{ album.album_name }}</p>
                <p class="artist">Artist: {{ album.artist }}</p>
                <p class="genre">{{ album.genre }}</p>
                <p class="price">Price: ${{ album.price }}</p>
            </div>
            <div class="btn-group">
                <a href="{% url 'details album' album.id %}">Details</a>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- End First Card-Box in catalog -->
    {% endif %}

</section>
{% endblock %}

python_web/basics/music_app/templates/profile-delete.html
{% extends 'base.html' %}
{% block site_content %}
<!-- Delete Profile Page-->
<section id="detailsPage">
    <div class="wrapper">
        <div class="profileText">

            <!-- Delete Profile Form -->
            <h1>Are you sure you want to delete your profile?</h1>
            <form method="post" action="{% url 'delete profile' %}">
                <!-- Confirm Button -->
                {% csrf_token %}
                <button class="delete-profile" type="submit">Delete</button>
            </form>
            <!-- End Delete Profile Form -->

        </div>
    </div>
</section>
{% endblock %}

python_web/basics/music_app/templates/profile-details.html
{% extends 'base.html' %}
{% block site_content %}
<!--Details Page-->
<section id="detailsPage">
    <div class="wrapper">
        <div class="profilePage">
            <img src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png"
                alt="Profile Image">
        </div>

        <div class="profileText">
            <!-- Profile Info -->
            <h1>Username: {{ profile.username.username }}</h1>
            <h1>Email: {{ profile.email }}</h1>
            {% if profile.age %}
            <h1>Age: {{ profile.age }}</h1>
            {% endif %}
            <h1>Albums: {{ user.album_set.count }}</h1>
        </div>

        <div class="actionBtn">
            <!-- Button for Deleting the Profile -->
            <a href="{% url 'delete profile' %}" class="remove">Delete</a>
        </div>

    </div>
</section>
{% endblock %}