python_web/basics/petstagram/common/urls.py
from django.urls import path

from common.views import main_page

urlpatterns = [
    path('', main_page, name='landing page'),
]

python_web/basics/petstagram/pets/urls.py
from django.urls import path

from pets.views import list_pets, details_or_comment_pet, like_pet, edit_pet, delete_pet, create_pet

urlpatterns = [
    path('', list_pets, name='list pets'),
    path('detail/<int:pk>', details_or_comment_pet,
         name='pet details or comment'),
    path('like/<int:pk>', like_pet, name='like pet'),
    path('edit/<int:pk>', edit_pet, name='edit pet'),
    path('delete/<int:pk>', delete_pet, name='delete pet'),
    path('create/', create_pet, name='create pet'),
]

python_web/basics/petstagram/petstagram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('pets/', include('pets.urls')),
]

python_web/basics/petstagram/pets/models.py
from django.db import models


class Pet(models.Model):

    CAT = 'Cat'
    DOG = 'Dog'
    PARROT = 'Parrot'
    DEFAULT = 'Unknown'

    PET_TYPES = [
        (CAT, 'Cat'),
        (DOG, 'Dog'),
        (PARROT, 'Parrot'),
        (DEFAULT, 'Unknown'),

    ]

    type = models.CharField(max_length=8, choices=PET_TYPES, default=PET_TYPES)
    name = models.CharField(max_length=6, blank=False)
    age = models.PositiveIntegerField(blank=False)
    description = models.TextField(blank=False)
    image_url = models.URLField(blank=False)

    def __str__(self):
        return f"{self.id} {self.name} {self.age}"


class Like(models.Model):
    like = models.ForeignKey(Pet, on_delete=models.CASCADE)
    comment = models.CharField(max_length=5)


class Comment(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    text = models.TextField(blank=False)

python_web/basics/petstagram/pets/forms.py
from typing import Any, Dict, Mapping, Optional, Type, Union
from django import forms
from django.core.files.base import File
from django.db.models.base import Model
from django.forms.utils import ErrorList

from pets.models import Pet


class CommentForm(forms.Form):
    text = forms.CharField(
        widget=forms.Textarea(
            attrs={'class': 'form-control rounded-2'}
        )
    )

class EditPetForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        
        for (_, field) in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
    class Meta:
        model = Pet
        fields = '__all__'
        widgets = {
            'image_url': forms.TextInput(
                attrs={'id': 'img_input'}
            )
        }
    
 

python_web/basics/petstagram/common/views.py
from django.shortcuts import render


# Create your views here.
def main_page(request):
    return render(request, 'landing_page.html',)

python_web/basics/petstagram/pets/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from pets.forms import CommentForm, EditPetForm

from pets.models import Pet, Like, Comment


def list_pets(request):
    context = {
        'pets': Pet.objects.all(),
    }
    return render(request, 'pet_list.html', context)


def details_or_comment_pet(request, pk):
    pet = Pet.objects.get(pk=pk)
    if request.method == 'GET':
        context = {
            'pet': pet,
            # you can also pass comments as context instead of loading comments as a set in the view
            # 'comments': Comment.objects.filter(pet=pet_obj)
            'form': CommentForm(),
        }
        return render(request, 'pet_detail.html', context)
    else:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(pet=pet, text=form.cleaned_data['text'])
            comment.save()
            return redirect('pet details or comment', pk)
        else:       
            context = {
                'pet': pet,
                'form': form,
            }
            return render(request, 'pet_detail.html', context)
        
def like_pet(request, pk):
    pet = Pet.objects.get(pk=pk)
    like = Like(comment=str(pk))
    like.like = pet
    like.save()
    return redirect('pet details or comment', pk)
 
def delete_pet(request,pk):  
    pet = Pet.objects.get(pk=pk)
    if request.method == 'POST':
        pet.delete()
        return redirect('list pets')
    
    else:
        context = {
        'pet': pet
        }  
        return render(request, 'pet_delete.html', context)
            
def persist_pet(request, pet=None, template_name='pet_edit.html'):
    if pet is None:
        pet = Pet()   
    
    if request.method == 'GET':
        form = EditPetForm(instance=pet)
        context = {
            'pet': pet,
            'form': form,
        }
        return render(request, template_name, context)
    
    else:
        form = EditPetForm(request.POST, instance=pet)
        if form.is_valid():
            form.save()
            return redirect('pet details or comment', pet.id)
        else:
            context = {
                'pet': pet,
                'form': form,
            }
            return render(request, template_name, context)
 

def edit_pet(request, pk):
    pet = Pet.objects.get(pk=pk)        
    return persist_pet(request, pet, 'pet_edit.html')
 
def create_pet(request):
    return persist_pet(request, template_name='pet_create.html')



# def edit_pet(request, pk):
#     pet = Pet.objects.get(pk=pk)    
#     if request.method == 'GET':
#         form = EditPetForm(instance=pet)
#         context = {
#             'pet': pet,
#             'form': form,
#         }
#         return render(request, 'pet_edit.html', context)
    
#     else:
#         form = EditPetForm(request.POST, instance=pet)
#         if form.is_valid():
#             form.save()
#             return redirect('pet details or comment', pet.id)
#         else:
#             context = {
#                 'pet': pet,
#                 'form': form,
#             }
#             return render(request, 'pet_edit.html', context)
 
 
# def create_pet(request):
#     if request.method == 'GET':
#         form = EditPetForm()
#         context = {
#             'form': form,
#         }
#         return render(request, 'pet_create.html', context)
    
#     else:
#         form = EditPetForm(request.POST, instance=Pet())
#         if form.is_valid():
#             new_pet_instance = form.save()
#             return redirect('pet details or comment', new_pet_instance.id)
#         else:
#             context = {
#                 'form': form,
#             }
#             return render(request, 'pet_create.html', context)
      

python_web/basics/petstagram/templates/handmade/index.html
{% extends 'shared/site.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block site_title %}
Welcome to Petstagram
{% endblock %}
{% block site_content %}
<section class="banner">
    <header>
        <h1>Welcome to Petstagram</h1>
        <h2>Share your pets photos.</h2>
    </header>
    <div class="row">
        <div class="col">
            Already have an account?
            <button class="button">Sign in</button>
        </div>
        <div class="col">
            Do you have an account?
            <a href="#" class="button">Sign up</a>
        </div>
    </div>
</section>
{% endblock %}

python_web/basics/petstagram/templates/handmade/pets/pets_details.html
{% extends 'shared/site.html' %}
{% load static %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/details-pet.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
{% endblock %}
{% block site_content %}
<div class="pet-image">
    <img src={{pet.image_url}} alt="image of {{ pet.name }}">
</div>
<div class="pet-info">
    <ul class="list-pet-details list-horizontal">
        <li class="list-item"><span class="underline">Type</span>: {{pet.type}}</li>
        <li class="list-item"><span class="underline">Name</span>: {{pet.name}}</li>
        <li class="list-item"><span class="underline">Age:</span> {{pet.age}}</li>
    </ul>
    <p>Description: {{pet.description}}</p>
    <a href="{% url 'like pet' pet.id %}"> <i class="fa-regular fa-heart"></i></a>
    <p>Likes: {{ pet.like_set.count }}</p>
</div>
{% endblock %}

python_web/basics/petstagram/templates/handmade/pets/pets_list.html
{% extends 'shared/../shared/site.html' %}
{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/list-pets.css' %}">
{% endblock %}

{% block site_content %}
<h1>All pets</h1>
<ul class="list-horizontal list-pets">
    {% for pet in pets %}
    <li class="list-item">
        <div class="image-container">
            <img src="{{ pet.image_url }}" alt="image of {{ pet.name }}">
        </div>
        <div class="pet-details">
            <p class="pet-info">{{ pet.type }} {{ pet.name }}, Age: {{ pet.age }}</p>
            <p class="pet-description">{{ pet.description }}</p>
            <div class="pet-buttons">
                <a class="button button-blue" href="{% url 'pet details' pet.id %}">
                    {{ pet.name }}
                </a>
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

python_web/basics/petstagram/templates/handmade/shared/site.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block site_title %}Petstagram{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/clear.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block styles %}
    {% endblock %}
</head>
<body>
{% include 'partials/nav.html' %}
<div id="root">
    {% block site_content %}
    Petstagram
    {% endblock %}
</div>
</body>
</html>